# Generated by Django 5.0.2 on 2024-04-03 11:35

from django.db import migrations
import openpyxl
from django.core.exceptions import ValidationError

def insert_countries(apps, schema_editor):
    Country = apps.get_model('mashinani', 'Country')
    
    try:
        # Load data from Excel workbook
        wb = openpyxl.load_workbook('mashinani/data/data.xlsx')
        sheet = wb['Country']
        
        # Extract institution names from the Excel sheet
        countries_data = []
        for row in sheet.iter_rows(min_row=2, values_only=True):  # Assuming data starts from second row
            country_name = row[0]  # Assuming country name is in the first column
            countries_data.append({'country_name': country_name})
        
        # Insert data into the model
        for data in countries_data:
            try:
                Country.objects.create(**data)
            except ValidationError as e:
                print(f"Validation Error: {e}")
    except FileNotFoundError:
        print("File not found. Please check the path to the Excel file.")
    except Exception as e:
        print(f"An error occurred: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('mashinani', '0004_auto_20240403_1340'),
    ]

    operations = [
        migrations.RunPython(insert_countries)
    ]
